My portfolio desktop version
Taher-web-dev/Portfolio-setup-and-mobile-version-skeleton pull request #6
Opened 2021-09-23 08:54 UTC by Taher-web-dev

## This branch contains the following changes: 

- Re-engineering  of html file. 
- Media query in css file to fit desktop version.

So, please take a look and give me your feedback before to merge with master branch.

2021-09-23 17:54 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @taherhagui  , You did a great job so far 👏🏼 👏🏼 

- The linter checks are passing.
- The repository is professional.
- the Readme is descriptive.

However, here are some points that you need to work on to get your project approved.

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Using one media query instead of many media queries for the same breakpoint. 

 Usind ong

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-23 17:54 UTC, safafa commented on styles/template2.css
> +@media screen and (min-width: 750px) {
- [ ] For the Desktop breakpoint the value for `min-width` property should be in range of `992px - 1100px` your break point is 750px kindly fix the issue.

![image](https://user-images.githubusercontent.com/43698511/134555217-dd07d45c-3e10-4ef0-9f03-ed5076512203.png)
original design :
![image](https://user-images.githubusercontent.com/43698511/134555301-16c1c967-e105-4692-afd6-04016171f40a.png)

- [ ] As you can see from the pictures for the desktop view the headline section looks a bit different from the one in the original design. The background image doesn't fit the whole screen. Kindly fix the issue.

![image](https://user-images.githubusercontent.com/43698511/134557638-69d3f02b-45dc-4841-82f3-ea305ce2a756.png)
original design:
![image](https://user-images.githubusercontent.com/43698511/134555956-d0958518-2e77-48ac-a7e0-c50f9a8a66e3.png)

- [ ] The project's cards also look a bit different from the original design. I think you need to adjust the margins and center the cards. Kindly fix the issue.

original design : 
![image](https://user-images.githubusercontent.com/43698511/134556815-c1618bf1-411f-45a3-88ea-d4ba723045e3.png)
your webpage:
![image](https://user-images.githubusercontent.com/43698511/134556873-e1c4fade-e9d0-49b3-bb63-196b004a4fc7.png)

- [ ] The about me section also looks a bit different. It has 2 blocks The left one takes 40% and the right one the remaining 60% of the page's width. The elements of each bloc are aligned to the right. The languages cards and the borders for the technologies look also different Kindly fix the issue.

![image](https://user-images.githubusercontent.com/43698511/134557451-8f07d9d0-367d-4276-9cf6-2b6e63052fb9.png)
![image](https://user-images.githubusercontent.com/43698511/134558107-c4e40912-d890-474a-9908-96c1fdc4a1e9.png)
mobile view:
![image](https://user-images.githubusercontent.com/43698511/134558281-64106718-4752-4925-babf-0441e8c30ab2.png)

original design:
![image](https://user-images.githubusercontent.com/43698511/134557772-6c0d3129-8f4d-4553-ba0d-48d6d48e9d68.png)
mobile view:
![image](https://user-images.githubusercontent.com/43698511/134558385-4408dcfd-4037-43f9-b944-08d300e53506.png)

- [ ] Kindly fix the background image of the contact-me section for desktop and mobile view.

2021-09-25 02:58 UTC, Alexoid1 requested changes
# Hi @Taher-web-dev,

Impressive project!
You are doing a great job so far, and the project is looking good.

## Required Changes :recycle:
For the project to get approved, also implement the changes mentioned below.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-25 02:58 UTC, Alexoid1 commented on index.html
>          <section id="p1">
- [ ] Kindly add a background color for the body `#E5E5E5` and for the sections set a #FFF background. This is what makes look your project different from the original design.
![Captura de pantalla_2021-09-24_21-11-08](https://user-images.githubusercontent.com/53111464/134754433-9656d04f-c1ce-4a43-8388-fd96e0dc8606.png)

**Figma**
![Captura de pantalla_2021-09-24_21-05-09](https://user-images.githubusercontent.com/53111464/134754413-afa06dd0-dc57-4ddf-8a21-84ef44565355.png)

2021-09-25 02:58 UTC, Alexoid1 commented on index.html
>          <section id="home_presentation">
- [OPTIONAL] Kindly style the bottom of the `home_presentation` section as the original design. The `border-bottom has a rounded corner.
![Captura de pantalla_2021-09-24_21-18-57](https://user-images.githubusercontent.com/53111464/134754791-e831eeb1-fda7-4461-8428-05863b797f6c.png)

2021-09-25 02:58 UTC, Alexoid1 commented on index.html
> +                     <a href="#">See Project</a>
- [OPTIONAL] For each `See Project` button the text color change to white on hover.

2021-09-25 02:58 UTC, Alexoid1 commented on index.html
> +                </ul>
- [ ] The languages section looks quite different than the original design the alignment change to row and the containers turn to squares with the logo at the top-left corner.
![Captura de pantalla_2021-09-24_21-47-40](https://user-images.githubusercontent.com/53111464/134755381-31b8057b-031e-4ae3-9102-9413b5630135.png)

**Figma**
![Captura de pantalla_2021-09-24_21-47-23](https://user-images.githubusercontent.com/53111464/134755394-098bdaf1-270b-47b4-9944-76f621329e48.png)

2021-09-25 02:58 UTC, Alexoid1 commented on index.html
> +                </ul>
- [OPTIONAL] The container also has a rounded corner.
![Captura de pantalla_2021-09-24_21-49-36](https://user-images.githubusercontent.com/53111464/134755441-1b44dde0-0d62-4228-bd5b-313d88bcdcd4.png)

2021-09-25 14:21 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Taher-web-dev , 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-25 15:38 UTC, merged